# Generated by Django 6.0.4 on 2026-04-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='emoji',
            field=models.CharField(default='🛍️', max_length=8),
        ),
        migrations.AddField(
            model_name='category',
            name='hero_gradient',
            field=models.CharField(default='135deg,#ede8df 0%,#faf7f3 100%', max_length=200),
        ),
        migrations.AddField(
            model_name='category',
            name='tagline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
